# Generated by Django 3.0.4 on 2020-03-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aa_1', models.CharField(max_length=100)),
                ('aa_2', models.CharField(max_length=100)),
                ('aa_3', models.CharField(max_length=100)),
                ('aa_4', models.CharField(max_length=100)),
            ],
        ),
    ]
